name: Ping Web Site

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule: 
    - cron: 0 */1 * * * 
jobs:
  ping:

    runs-on: ubuntu-latest
    environment: 
      name: webhook
    permissions:
      
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Ping IP
      run: |
        sudo apt-get install -y tcptraceroute bc
        sudo chmod +x ./tcping
        sudo mv tcping /usr/local/bin/tcping
       
        
    - name: Ping IP
      env:
        WEBHOOK: ${{ secrets.WEBHOOK }}
      run: |
        sudo chmod +x domainping.sh
        ./domainping.sh "cyht.eu.org 81"
        sudo chmod +x rustdesk.sh
        ./rustdesk.sh "cyht.eu.org"
       
        
        
        
    
    
